version: '3.8'
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - 'postgres_data:/var/lib/postgresql/data:rw'
    ports:
      - "5432:5432"
    networks:
      - dezoomcamp-networks
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - dezoomcamp-networks

volumes:
  postgres_data:

networks:
  dezoomcamp-networks:
    driver: bridge
    